### ISSUE TITLE
Potential Bugs about postprocess in BSP?

### ISSUE THREAD

**Issue by Skyfall-xzz** [casmlab/NPHardEval#1]
Thanks for your great work!

In https://github.com/casmlab/NPHardEval/blob/49440d0569185f3eb0d80cd87e3b4f0bf8bf4e62/run/run_close_zeroshot/run_p_BSP.py#L74 
, llm_string has been processed to dict via parse_xml_to_dict and stored in "output". However in https://github.com/casmlab/NPHardEval/blob/49440d0569185f3eb0d80cd87e3b4f0bf8bf4e62/check/check_p_BSP.py#L35 , bsp_check function parse "output" again and assert xml elements in it. This leads to the return value of bsp_check always being False thus the result of bsp task will always be 0. Remove the code in https://github.com/casmlab/NPHardEval/blob/49440d0569185f3eb0d80cd87e3b4f0bf8bf4e62/check/check_p_BSP.py#L35 will fix it if I understand correctly.

Meanwhile, DATA_PATH in all run_xxx.py need to be fixed. For instance in  https://github.com/casmlab/NPHardEval/blob/49440d0569185f3eb0d80cd87e3b4f0bf8bf4e62/run/run_close_zeroshot/run_cmp_GCP_D.py#L28 , DATA_PATH should be '../../Data/Zeroshot/GCP_Decision/' if I understand correctly.

**Comment by lizhouf** [comment]
Thanks for figuring this out. Please try the new version we released today - it should fix these bugs. If there are more bugs spotted, please let me know.
